### ISSUE TITLE
htmlunit-client 1.1.5 is not compatible with htmlunit 2.57.0 and Jquery 3.7.0

### ISSUE THREAD

**Issue by Mohana-Priya** [HtmlUnit/htmlunit#615]
Hi we have a project build on richfaces 4.0.0. Iam trying to upgrade Jquery from 1.5.1 to 3.7.0. After upgrading Jquery, I upgraded htmlunit and htmlunit-core-js to 2.67.0 from 2.17 . But still my tests are failing with error 
java.lang.NoSuchMethodError: com.gargoylesoftware.htmlunit.WebRequest.getCharset()Ljava/lang/String;
	at org.jboss.test.faces.htmlunit.LocalWebConnection.getResponse(LocalWebConnection.java:52)
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseFromWebConnection(WebClient.java:1597)
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponse(WebClient.java:1519)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:498)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:413)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:551)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:533)
	at org.jboss.test.faces.htmlunit.HtmlUnitEnvironment.getPage(HtmlUnitEnvironment.java:90)

Which means the htmlunit-client which iam using is not compatible with htmlunit and html-core-js.

<dependency>
				<groupId>org.jboss.test-jsf</groupId>
				<artifactId>htmlunit-client</artifactId>
				<version>1.1.5</version>
			</dependency>
<dependency>
				<groupId>net.sourceforge.htmlunit</groupId>
				<artifactId>htmlunit</artifactId>
				<version>2.67.0</version>
			</dependency>
			<dependency>
				<groupId>net.sourceforge.htmlunit</groupId>
				<artifactId>htmlunit-core-js</artifactId>
				<version>2.67.0</version>
			</dependency>

Could you please let me know how to solve this?

**Comment by rbri** [comment]
The return type of the method .WebRequest.getCharset() was changed in version 2.25. (https://www.htmlunit.org/changes-report.html#a2.25)

Because of this the richfaces? class org.jboss.test.faces.htmlunit.LocalWebConnection is no longer compatible with HtmlUnit 2.25 and above.
The best approach would be to upgrade the jboss stuff - but i have no idea where this comes from and if this is still maintained.

**Comment by rbri** [comment]
Ok, found something - https://mvnrepository.com/artifact/org.jboss.test-jsf/htmlunit-client/1.1.9

There is also the source code available - maybe we can discuss to make an (private) update of this using the latest HtmlUnit.

**Comment by Mohana-Priya** [comment]
Hi thanks for the reply. I tried with 1.1.9 of htmlunit-client artifact but same error message. Is there any other alternative for htmlunit-client?

**Comment by rbri** [comment]
> I tried with 1.1.9 of htmlunit-client artifact but same error message

Yes that is expected!
What i like to say is you need an adjusted version of the htmlunit-client artifact that uses the current htmlunit.

I guess i can build such an version - but i can only do it if you are paying for my work on this adjustment.
Is this an option for you (i guess you work is done in a business context)?

**Comment by Mohana-Priya** [comment]
Hi Iam trying to download source code for htmlunit-client jar and modify the source code compatible with htmlunit 2.57.0
If Iam unable to do I will contact you back thanks!

**Comment by rbri** [comment]
Great plan :-)
but why using htmlunit 2.57.0 and not a more recent version?

**Comment by Mohana-Priya** [comment]
Hi tired htmlunit 2.67.0 i think this is the latest compatible with richfaces 4.0.
And I tried overriding two classes in my project and could resolve the problem.


Thanks,
Mohana.

**Comment by rbri** [comment]
> And I tried overriding two classes in my project and could resolve the problem.

Great!

> Hi tired htmlunit 2.67.0 i think this is the latest compatible with richfaces 4.0.

Why do you think 2.67.0 is the last one?

HtmlUnit tries to mimic recent browsers as close as possible and every release is better/closer than the one before. And i guess your richfaces app still works with recent browsers.

**Comment by rbri** [comment]
@Mohana-Priya will close this - hope this is ok for you. If not please reopen...

Thanks for using HtmlUnit.
