### ISSUE TITLE
HtmlUnit 2.35 breaks server (jetty, NoClassDefFoundError)

### ISSUE THREAD

**Issue by black-snow** [HtmlUnit/htmlunit#36]
When I update from HtmlUnit 2.34.1 to 2.35.0 my testing tool's server breaks. It's using Dropwizard and includes Jetty. From what I understand HtmlUnit ships with a newer Jetty version and as I use the shade plugin to create a jar file only one of the Jetties is included and my dropwizard cannot find the SSlContextFactory Client anymore.

```
INFO   [12:23:50.407]  Opened admin@44032fde{HTTP/1.1,[http/1.1]}{0.0.0.0:8081}
java.lang.NoClassDefFoundError: org/eclipse/jetty/util/ssl/SslContextFactory$Client
        at org.eclipse.jetty.websocket.client.HttpClientProvider.get(HttpClientProvider.java:49)
        at org.eclipse.jetty.websocket.client.WebSocketClient.<init>(WebSocketClient.java:268)
        at org.eclipse.jetty.websocket.jsr356.ClientContainer.<init>(ClientContainer.java:137)
        at org.eclipse.jetty.websocket.jsr356.server.ServerContainer.<init>(ServerContainer.java:99)
        at org.eclipse.jetty.websocket.jsr356.server.ServerContainer.<init>(ServerContainer.java:89)
        ...
```

I currently have no idea how to fix this and I doubt that this is an issue with HtmlUnit but rather with java and building a fat jar. I'll document it here anyway.

**Comment by black-snow** [comment]
The only way to go seems to be [relocating](https://bryantsai.com/how-to-resolve-dependency-conflict-out-of-your-control-e75ace79e54f) either dropwizard or htmlunit ... or waiting for dropwizard to hit a compatible jetty version again. Java's dependency management really is a mess when building fat jars :(

**Comment by black-snow** [comment]
I'll stick with 2.34.1 for now.

**Comment by rbri** [comment]
Have reverted the change, you can now use the latest 2.36-0-SNAPSHOT

**Comment by black-snow** [comment]
Thanks, no issues with *2.36.0-SNAPSHOT* so far.

**Comment by black-snow** [comment]
I gotta revert that - actually still crashing @rbri :

```
java.lang.NoClassDefFoundError: org/eclipse/jetty/util/ssl/SslContextFactory$Client
        at org.eclipse.jetty.websocket.client.HttpClientProvider.get(HttpClientProvider.java:49)
        at org.eclipse.jetty.websocket.client.WebSocketClient.<init>(WebSocketClient.java:268)
        at org.eclipse.jetty.websocket.jsr356.ClientContainer.<init>(ClientContainer.java:137)
        at org.eclipse.jetty.websocket.jsr356.server.ServerContainer.<init>(ServerContainer.java:99)
        at org.eclipse.jetty.websocket.jsr356.server.ServerContainer.<init>(ServerContainer.java:89)
        at io.dropwizard.metrics.jetty9.websockets.InstWebSocketServerContainerInitializer.configureContext(InstWebSocketServerContainerInitializer.java:40)
        at io.dropwizard.websockets.WebsocketBundle$1.lifeCycleStarting(WebsocketBundle.java:104)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.setStarting(AbstractLifeCycle.java:188)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:67)
        at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:53)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:44)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:93)
        at xyz.FrontendTestingApplication.main(FrontendTestingApplication.java:58)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.util.ssl.SslContextFactory$Client
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 15 more
```

**Comment by rbri** [comment]
The new stacktrace has htmlunit inside. Maybe something is wrong with your classpath.

**Comment by black-snow** [comment]
With the new dropwizard `1.3.10` my error goes away (they upgraded jetty).
Thanks for the efforts @rbri !
