### PR TITLE
Css js decouple

### LINKED ISSUE #131: Support ComputedCSSStyleDeclaration when JS engine is disabled.
When initializing webClient without JSEngine, there's no way to access any computed styles because the API is based on JS pairing.

### PR DESCRIPTION
**Pull request by cdalexndr**
Can now use `DomElement.getComputedStyle()` to retrieve non-js `ComputedCssStyleDeclaration`.

`CssStyleDeclaration` has basic functionality without the helper methods to get specific styles, like those in `CSSStyleDeclaration` and `ComputedCSSStyleDeclaration`. (todo in future)

closes #131

### CODE REVIEW

**Comment by rbri** [comment]
Thanks for this large contribution - please give me some time for review.

**Comment by cdalexndr** [comment]
Found a bug regarding style inheritance, will commit fix soon...

**Comment by cdalexndr** [comment]
Actually it will be a larger commit to fix some issues.
I'll see if I can squash the commits for better review readability.

**Comment by cdalexndr** [comment]
Done. It seems the "Files changed" tab already squashed commits.

**Comment by rbri** [comment]
This is not forgotten - please be a bit more patient.

**Comment by cdalexndr** [comment]
Merged latest changes into the PR branch

**Comment by cdalexndr** [comment]
As more changes are added to `master` branch, it is becoming increasingly difficult to keep this PR up-to-date to merge those changes and resolve conflicts.

If you consider this PR useful, it should be addressed before it becomes too hard to merge.

**Comment by cdalexndr** [comment]
Encountered an issue trying to merge `master`:

https://github.com/HtmlUnit/htmlunit/commit/000cdfc8c0542d90b798e7dbde6f10c6cf573b72 added `CSSStyleDeclaration.item` property.
Accoding to [WebAPI docs](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/item), the return value is a `DomString`, but the added method returns a `com.gargoylesoftware.css.dom.Property`  object.

This is **conflicting** with my classes, and will change it to reflect WebAPI specification, returning `String` instead.

**Comment by cdalexndr** [comment]
Managed to merge `master` branch and resolve conflicts.

There are still some minor tests failing, regarding css value case sensitivity (introduced by https://github.com/HtmlUnit/htmlunit/commit/3cfa733a94f44942461c62f87ef9b3c296b37171). My code currently always returns lowercase.
For example `CSSStyleDeclaration3Test#borderCssColor`:
```
org.junit.ComparisonFailure: 
Expected :§§§§§§§§rEd§rEd§rEd§rEd§
Actual   :§§§§§§§§red§red§red§red§
```

This is also a reminder that delaying this PR will make it increasingly difficult to keep up to date with latest changes.

**Comment by cdalexndr** [comment]
Something is wrong with the autobuild check:
```
  Error: 1-04 18:06:16] [autobuild] [ERROR] /home/runner/work/htmlunit/htmlunit/src/main/java/com/gargoylesoftware/htmlunit/html/HtmlForm.java:[479,34] cannot find symbol
  Error: 1-04 18:06:16] [autobuild] [ERROR]   symbol:   variable ATTRIBUTE_DISABLED
  Error: 1-04 18:06:16] [autobuild] [ERROR]   location: class com.gargoylesoftware.htmlunit.html.HtmlForm
  Error: 1-04 18:06:16] [autobuild] [ERROR] /home/runner/work/htmlunit/htmlunit/src/main/java/com/gargoylesoftware/htmlunit/html/HtmlPage.java:[790,63] cannot find symbol
  Error: 1-04 18:06:16] [autobuild] [ERROR]   symbol:   variable ATTRIBUTE_DISABLED
  Error: 1-04 18:06:16] [autobuild] [ERROR]   location: class com.gargoylesoftware.htmlunit.html.HtmlPage
```
But there is no `ATTRIBUTE_DISABLED` text in `HtmlForm.java` or `HtmlPage.java` on this branch, and the local build works.

**Comment by rbri** [comment]
@cdalexndr this was a real long way to go - sorry for that
I think this is finally landed in the code base with my last changes.

Many, many thanks for this - i used it as template and as motivation!

Hope you still use HtmlUnit i you will provide more PR's in the future.
